version: "3.8"

services:
  web:
    image: gagal1818/mnr_web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network

  docs:
    image: gagal1818/mnr_docs:latest
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
