version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile  # Specify the Dockerfile location if different
    ports:
      - "3000:3000"  # Expose port 3000 for app1
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network

  docs:
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile  # Specify the Dockerfile location if different
    ports:
      - "3001:3000"  # Expose port 3001 for app2
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
