version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network

  docs:
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
